// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClttlSkw3XYbcZjqRDplQ6QXc-ivV6tvo',
    appId: '1:1016648775638:web:36250d026d0def0d2cd677',
    messagingSenderId: '1016648775638',
    projectId: 'skin-cancer-detection-94fe3',
    authDomain: 'skin-cancer-detection-94fe3.firebaseapp.com',
    storageBucket: 'skin-cancer-detection-94fe3.appspot.com',
    measurementId: 'G-6TN7DND0W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzOeJW_XET86pUpvbAbY6YBPousyciBds',
    appId: '1:1016648775638:android:35a3add01c94de2b2cd677',
    messagingSenderId: '1016648775638',
    projectId: 'skin-cancer-detection-94fe3',
    storageBucket: 'skin-cancer-detection-94fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlaaC28EuhKYCEtBJQNLYQCAYIHvA4js',
    appId: '1:1016648775638:ios:cf5fcb1fb2346e262cd677',
    messagingSenderId: '1016648775638',
    projectId: 'skin-cancer-detection-94fe3',
    storageBucket: 'skin-cancer-detection-94fe3.appspot.com',
    iosBundleId: 'com.skinlesiondetector.skinlesiondetector',
  );
}
